spring.application.name=SkrzypekAPP
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/SkrzypekAPP
spring.datasource.username=mateuszskrzypek
spring.datasource.password=${DB_PASSWORD}


app.jwt-secret=C2Ayx3taWGsRFtg/hTq4nrK2Wdm65tAIIUihYf9E7L2HE3yZxs3yTCnzjiB/B80V8lG8UyxN3PEGSz6JjTGIvQ==
app.jwt-expiration-milliseconds=86400000